# Numpy Operations

In [1]:
import numpy as np

### Find the dimension of the array

In [2]:
a = np.array([1,2,3])
print(a.ndim)

1


In [3]:
a = np.array([(1,2,3),(3,4,5)])
print(a.ndim)

2


### Find the byte size of each element

In [4]:
a = np.array([5,9,7])
print(a.itemsize)

4


### Find the data type of the elements

In [5]:
a = np.array([98,56,25])
print(a.dtype)

int32


### Find the size of an array

Total number of elements that are present in an array.

In [6]:
a = np.array([1,2])
print(a.size)

2


In [7]:
a = np.array([1,2,3,4,5])
print(a.size)

5


In [8]:
a = np.array([9,8,7,6,5,4,3,2,1])
print(a.size)

9


### Find the shape of an array

Total number of columns and rows of an array.

In [9]:
a = np.array([1,2,3,4,5,6,7])
print(a.shape)

(7,)


In [10]:
a = np.array([(1,2,3),(4,5,6)])
print(a.shape)

(2, 3)


### Arithmetic Operations
You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [21]:
a = np.arange(0,10)

In [22]:
a + a 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
a * a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [25]:
a / a
#Warning on division by zero, but not an error!
#Just replaced with nan

C:\Users\Promech-PC-5\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [26]:
1/a
#Also warning, but not an error instead infinity

C:\Users\Promech-PC-5\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [27]:
a**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [28]:
a = np.random.randint(0,25,10)

In [29]:
np.sqrt(a)

array([3.46410162, 2.23606798, 4.47213595, 3.46410162, 4.69041576,
       2.64575131, 1.        , 4.24264069, 4.89897949, 1.73205081])

In [30]:
np.exp(a)

array([1.62754791e+05, 1.48413159e+02, 4.85165195e+08, 1.62754791e+05,
       3.58491285e+09, 1.09663316e+03, 2.71828183e+00, 6.56599691e+07,
       2.64891221e+10, 2.00855369e+01])

In [31]:
np.max(a)

24

In [32]:
np.sin(a)

array([-0.53657292, -0.95892427,  0.91294525, -0.53657292, -0.00885131,
        0.6569866 ,  0.84147098, -0.75098725, -0.90557836,  0.14112001])

In [35]:
np.cos(a)

array([ 0.84385396,  0.28366219,  0.40808206,  0.84385396, -0.99996083,
        0.75390225,  0.54030231,  0.66031671,  0.42417901, -0.9899925 ])

In [36]:
np.tan(a)

array([-0.63585993, -3.38051501,  2.23716094, -0.63585993,  0.00885166,
        0.87144798,  1.55740772, -1.13731371, -2.1348967 , -0.14254654])

In [33]:
np.log(a)

array([2.48490665, 1.60943791, 2.99573227, 2.48490665, 3.09104245,
       1.94591015, 0.        , 2.89037176, 3.17805383, 1.09861229])

In [34]:
np.log10(a)

array([1.07918125, 0.69897   , 1.30103   , 1.07918125, 1.34242268,
       0.84509804, 0.        , 1.25527251, 1.38021124, 0.47712125])