# Numpy Array Attributes and Methods

Let's discuss some useful attributes and methods of an array.

In [11]:
import numpy as np

### Reshaping an array

Returns an array containing the same data with a new shape.

In [2]:
a = np.arange(25)

In [3]:
arr = a.reshape(5,5)

In [4]:
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


### Finding max, min, argmax and argmin of an array

These are useful methods to find max or min values. Or to find their index locations using argmax or argmin.

In [5]:
a = np.random.randint(0,50,10)

In [6]:
print(a)

[46 11  3 19 22  5 27 21 25  9]


In [7]:
print(a.max())

46


In [8]:
print(a.argmax())

0


In [9]:
print(a.min())

3


In [10]:
print(a.argmin())

2
